### ISSUE TITLE
Support Python 3.8?

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [dev-petrov/pytest-lazy-fixtures#2]
:wave: hi there, thanks for maintaining this package.  A brief look through the code doesn't show any language features from python >=3.9, but the pyproject.toml lists it as a requirement.  Would you be amenable to loosening support to 3.8?

**Comment by dev-petrov** [comment]
Hi! Yes, I will add support for 3.8

**Comment by dev-petrov** [comment]
Added in 1.0.1
