### ISSUE TITLE
How to unpack a fixture with lc?

### ISSUE THREAD

**Issue by stefanofusai** [dev-petrov/pytest-lazy-fixtures#26]
Hey, I'm trying to implement this package in my tests but I'm not succeeding in doing so.
Here's an example of my code:
```py
@pytest.fixture()
def my_models() -> list[MyModel]:
    return MyModelFactory.create_batch(CREATE_BATCH_SIZE)

@pytest.mark.parametrize("my_model", lf("my_models"))
def test_my_models(my_model: MyModel) -> None:
    ...
```
The error I get is the following:
```
_________________ ERROR collecting tests/website/views_test.py _________________
.venv/lib/python3.12/site-packages/pluggy/_hooks.py:513: in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
.venv/lib/python3.12/site-packages/pluggy/_manager.py:120: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
.venv/lib/python3.12/site-packages/_pytest/python.py:248: in pytest_pycollect_makeitem
    return list(collector._genfunctions(name, obj))
.venv/lib/python3.12/site-packages/_pytest/python.py:461: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
.venv/lib/python3.12/site-packages/pluggy/_hooks.py:574: in call_extra
    return self._hookexec(self.name, hookimpls, kwargs, firstresult)
.venv/lib/python3.12/site-packages/pluggy/_manager.py:120: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
.venv/lib/python3.12/site-packages/_pytest/python.py:118: in pytest_generate_tests
    metafunc.parametrize(*marker.args, **marker.kwargs, _param_mark=marker)
.venv/lib/python3.12/site-packages/_pytest/python.py:1209: in parametrize
    argnames, parametersets = ParameterSet._for_parametrize(
.venv/lib/python3.12/site-packages/_pytest/mark/structures.py:161: in _for_parametrize
    parameters = cls._parse_parametrize_parameters(argvalues, force_tuple)
.venv/lib/python3.12/site-packages/_pytest/mark/structures.py:147: in _parse_parametrize_parameters
    return [
E   TypeError: 'LazyFixtureWrapper' object is not iterable
```
Any idea of what I'm doing wrong?

**Comment by dev-petrov** [comment]
HI! You can't unpack lazy_fixture like this, because fixtures are resolving during test run, but parameters are resolving during test collection. To implement your test you should use list of different fixtures.

```python

@pytest.fixture()
def my_model1() -> MyModel:
    return MyModelFactory()

@pytest.fixture()
def my_model2() -> MyModel:
    return MyModelFactory()

@pytest.mark.parametrize("my_model", [lf("my_model1"), lf("my_model2")])
def test_my_models(my_model: MyModel) -> None:
    ...
```

**Comment by stefanofusai** [comment]
Thank you for the quick reply!
That's a shame because I wanted to replace for loops inside my tests with `@pytest.mark.parametrize`
Are there any other solutions you know of?

**Comment by stefanofusai** [comment]
Also, when you say _because fixtures are resolving during test run, but parameters are resolving during test collection_, is that a limitation of your package or of pytest itself?
If it's a limitation of your package I think it would be a worthy feature to add

**Comment by dev-petrov** [comment]
> Thank you for the quick reply!
> 
> That's a shame because I wanted to replace for loops inside my tests with `@pytest.mark.parametrize`
> 
> Are there any other solutions you know of?

You still can split your fixture into several fixtures as I said

**Comment by dev-petrov** [comment]
> Also, when you say _because fixtures are resolving during test run, but parameters are resolving during test collection_, is that a limitation of your package or of pytest itself?
> 
> If it's a limitation of your package I think it would be a worthy feature to add

It's how pytest works, I can't do anything with that
