### ISSUE TITLE
Problem with parametrized fixture as dependency of a lazy fixture

### ISSUE THREAD

**Issue by agronholm** [dev-petrov/pytest-lazy-fixtures#5]
If I have a parametrized fixture which a lazy fixture depends on, I get a collection error saying `The requested fixture has no parameter defined for test`. This worked fine with `pytest-lazy-fixture`, but not with this library.

A trivial example (comment/uncomment the relevant imports as needed):
```python
import pytest
# from pytest_lazy_fixtures import lf
from pytest_lazyfixture import lazy_fixture as lf


@pytest.fixture(params=[
    "a", "b"
])
def fixture1(request):
    return request.param


@pytest.fixture
def service1(fixture1):
    return 1


@pytest.fixture
def service2(fixture1):
    return 1


@pytest.fixture(params=[
    lf("service1"),
    lf("service2"),
])
def fixture2(request):
    return None


def test_foo(fixture2):
    pass
```

**Comment by harsanyidani** [comment]
Samme issue here

**Comment by dev-petrov** [comment]
Fixed in 1.0.5

**Comment by harsanyidani** [comment]
Indeed, thanks!

**Comment by agronholm** [comment]
The error is gone, thanks! I'm seeing some differences to investigate in my test suite, but it's possible they were problems exposed by this new plugin.
